# Week 4 - Data organising with Pandas

Author: Johanne Sejrskild  
Date: 22.09.2025

*Good afternoon*  
Today we are going to work with loops, condions and using ´pandas´to manipulate data. The green excercises will be highly linked to what you livecoded with Anna. If you find them challenging use yesterdays work as a help or ask. If you want to challenge yourself, try and do them all without using any help. 
In the yellow  excercises we will do some data manipulation challenges using pandas. And we will skip the red tasks today as we have a lot on the program

**Structure of the notebook:**  
<span style="color:green">
Green excercises 
</span>
<ul>
  <li> Data wrangling on the iris dataset</li>
</ul>

<span style="color:yellow">
Yellow excercises
</span>
<ul>
  <li>Music sales challenge</li>
  <li>Space mission challenge</li>
  <li>Supervillan challenge</li>
</ul>
 

Start with the first excercise, and then continue in order. Feel free to work together, and see how far you can get.   
The important thing is to learn, not to solve all the challenges!
________________________________________________________________________________________

In [2]:
# Before we start we need to import the necessary packages - ater you have run this chunk you can comment out the first three lines
#%pip install pandas
#%pip install lxml
#%pip install scikit-learn

import pandas as pd
import requests # We might need this package to get some data from the web
from sklearn import datasets
from io import StringIO

<span style="color:green">
<h2>
Green excercises </h2>
</span>

## Data organisation using a dataset about flowers

In [3]:
flower = datasets.load_iris()

# convert to DataFrame
df = pd.DataFrame(flower.data, columns=flower.feature_names)

df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


**Lets take a look at the data frame**

In [4]:
# There are some commands in the library pandas that can give you a quick overview of the data :)

df.head(3)      # first 5 rows, if you put a number into the paranthesis you can decide how many rows
df.tail()      # last 5 rows
df.info()      # summary of columns and types
df.describe()  # quick statistics (for numbers)

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

**Selecting columns and rows**

Try to run the cell below and figure out which output is linked to the code

In [13]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
# If you want to select a specific column you can select it using the name:
print(df['sepal length (cm)'].head())

# If you would like to print one row, you can use the index of the row:
print(df.iloc[0])

# if you want to select a few rows of only a few columns you can also use indexing:
print(df.iloc[0:3 , 0:2])  # first three rows, first two columns

# And if you want to select specific data, you can specify a single row and column:
print(df.iloc[2,0])  # second row, first column

# Or use the column name:
print(df.loc[2, "sepal length (cm)"]  )

0    5.1
1    4.9
2    4.7
3    4.6
4    5.0
Name: sepal length (cm), dtype: float64
sepal length (cm)    5.1
sepal width (cm)     3.5
petal length (cm)    1.4
petal width (cm)     0.2
Name: 0, dtype: float64
   sepal length (cm)  sepal width (cm)
0                5.1               3.5
1                4.9               3.0
2                4.7               3.2
4.7
4.7

**Subsetting data**   
Subsetting is the process of retrieving just the parts of large files which are of interest for a specific purpose.   
This will come in handy for your projects when you have to work with potentially large data files

In [14]:
# Let's try to select some data using conditionals

# Here we select all rows where the sepal length is larger than or equal to 5 cm
lengt_above_five = df[df["sepal length (cm)"] >= 5]   
lengt_above_five.head()

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                 5.1               3.5                1.4               0.2
4                 5.0               3.6                1.4               0.2
5                 5.4               3.9                1.7               0.4
7                 5.0               3.4                1.5               0.2
10                5.4               3.7                1.5               0.2

In [15]:
# Here we select all rows where the sepal length is larger than or equal to 5 cm and the sepal width is less than 2,5 cm
length_and_width = df[(df["sepal length (cm)"] >= 5) & (df["sepal width (cm)"] < 3.5)]
length_and_width.head()

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
7                 5.0               3.4                1.5               0.2
20                5.4               3.4                1.7               0.2
23                5.1               3.3                1.7               0.5
25                5.0               3.0                1.6               0.2
26                5.0               3.4                1.6               0.4

In [ ]:
# Excercise - Find the longest petal length and the median petal length

max_petal_length = df['petal length (cm)'].max()
print(max_petal_length)

median_petal = df['petal length (cm)'].median()
print(median_petal)


# and subset the flowers that are between the median and one centimeter shorter than max length

subset_flowers_df = df[(df['petal length (cm)'] > median_petal) & (df['petal length (cm)'] < (max_petal_length-1))]
subset_flowers_df

6.9
4.35

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
50                 7.0               3.2                4.7               1.4
51                 6.4               3.2                4.5               1.5
52                 6.9               3.1                4.9               1.5
54                 6.5               2.8                4.6               1.5
55                 5.7               2.8                4.5               1.3
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[62 rows x 4 columns]

**Sorting data**  
We can choose to sort our data in order of something of interest.

In [33]:
# we could sort the data by a specific column in both ascending and descending order
df_sorted = df.sort_values(by="sepal length (cm)", ascending=False) # change direction by True/False so if you want ascending order set it to True
df_sorted.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
131                7.9               3.8                6.4               2.0
122                7.7               2.8                6.7               2.0
118                7.7               2.6                6.9               2.3
117                7.7               3.8                6.7               2.2
135                7.7               3.0                6.1               2.3

In [ ]:
# Excercise - sort the data by petal width in ascending order and select the 10 flowers with the smallest petal width

df_sorted_pwidth = df.sort_values(by=["petal width (cm)"], ascending = True) # the data sorted by petal width
df_sorted_pwidth

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
12                 4.8               3.0                1.4               0.1
13                 4.3               3.0                1.1               0.1
9                  4.9               3.1                1.5               0.1
32                 5.2               4.1                1.5               0.1
37                 4.9               3.6                1.4               0.1
..                 ...               ...                ...               ...
136                6.3               3.4                5.6               2.4
114                5.8               2.8                5.1               2.4
109                7.2               3.6                6.1               2.5
100                6.3               3.3                6.0               2.5
144                6.7               3.3                5.7               2.5

[150 rows x 4 columns]

In [ ]:

smallest_width = df_sorted_pwidth[0:10] # the new df starts with the lowest widths, so we simply take the first 10 rows
smallest_width

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
12                4.8               3.0                1.4               0.1
13                4.3               3.0                1.1               0.1
9                 4.9               3.1                1.5               0.1
32                5.2               4.1                1.5               0.1
37                4.9               3.6                1.4               0.1
1                 4.9               3.0                1.4               0.2
4                 5.0               3.6                1.4               0.2
0                 5.1               3.5                1.4               0.2
11                4.8               3.4                1.6               0.2
10                5.4               3.7                1.5               0.2

**Flipping**  
Should you work with time seires data and would like to mirror (flip) your data, you can do this using pandas

In [39]:
print(df.head(5))

reversed_df = df.iloc[::-1]   # Flipping the dataframe horisontally (reverse rows)

print(reversed_df.head(5))

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
149                5.9               3.0                5.1               1.8
148                6.2               3.4                5.4               2.3
147                6.5               3.0                5.2               2.0
146                6.3               2.5                5.0               1.9
145                6.7               3.0                5.2               2.3

**Joining**
Sometimes we have multiple dataframes we woudl like to add together. Maybe you have been subsetting parts of an old dataframe to substract important information and would now like join them so you can begin your analysis.

In [48]:
# Joining a bit of the iris data with a new dataframe (we will make up some data here)
first_10 = df.iloc[0:10, :]  # selecting the first 10 rows of the iris data
new_data = {"color": ["red", "blue", "green", "yellow", "purple", "red", "blue", "green", "yellow", "purple"],
            "height": [80, 80, 70, 100, 90, 80, 80, 70, 100, 90]}
# Right now new_df is a dictionary, we need to convert it to a dataframe
new_df = pd.DataFrame(new_data)

#Now we join the two dataframes
joined = first_10.join(new_df, how='left') # There are 4 different types of how: outer, inner, left, right. 

joined

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90

*Different types of how to join two data frames*  
This is important if your dataframes do not have the same amount of rows

left → all rows from the left DataFrame - and the ones matching from the right.

right → all rows from the right DataFrame - and the ones matching from the right.

inner → only rows with matching index values (rows) in both.

outer → all rows from both, fill missing with NaN.

In [ ]:
# Excercise - Which types of join (the 'how=') will work in the example above? Try them out and see what happens
## Answer:
## - right: gives same result as left
## - inner: same result
## - outer: same result

joined = first_10.join(new_df, how='outer') # There are 4 different types of how: outer, inner, left, right. 

joined

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90

In [ ]:
# Excercise 2 - Add a row to one of the dataframes and see what happens when you join them again
first_10 = df.iloc[0:10, :]  # selecting the first 10 rows of the iris data
new_data = {"color": ["red", "blue", "green", "yellow", "purple", "red", "blue", "green", "yellow", "purple", "new row color"],
            "height": [80, 80, 70, 100, 90, 80, 80, 70, 100, 90, 100]}
# Right now new_df is a dictionary, we need to convert it to a dataframe
new_df = pd.DataFrame(new_data)

#Now we join the two dataframes
joined = first_10.join(new_df, how='outer') # There are 4 different types of how: outer, inner, left, right. 

joined

# left: removes row 10
# right: adds row 10 and NaN values
# inner: removes row 10
# outer: adds row 10 and NaN values

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),color,height
0,5.1,3.5,1.4,0.2,red,80
1,4.9,3.0,1.4,0.2,blue,80
2,4.7,3.2,1.3,0.2,green,70
3,4.6,3.1,1.5,0.2,yellow,100
4,5.0,3.6,1.4,0.2,purple,90
5,5.4,3.9,1.7,0.4,red,80
6,4.6,3.4,1.4,0.3,blue,80
7,5.0,3.4,1.5,0.2,green,70
8,4.4,2.9,1.4,0.2,yellow,100
9,4.9,3.1,1.5,0.1,purple,90
10,NaN,NaN,NaN,NaN,new row color,100

**Concatenating**  
You can also join two dataframes bu simply gluing them together.

In [62]:
# We just made a subset of the original dataframe called 'first_10' now we find the last 10 and glue them together
last_10 = df.iloc[-10:, :]   # selecting the last 10 rows using one of the methods we learned above


# Now we concatenate the two dataframes together 
concatenated = pd.concat( [first_10, last_10], axis=0)  # axis=0 means we concatenate rows, axis=1 would concatenate columns
concatenated

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
6                  4.6               3.4                1.4               0.3
7                  5.0               3.4                1.5               0.2
8                  4.4               2.9                1.4               0.2
9                  4.9               3.1                1.5               0.1
140                6.7               3.1                5.6               2.4
141                6.9               3.1                5.1               2.3
142                5.8               2.7                5.1               1.9
143                6.8               3.2                5.9               2.3
144                6.7               3.3                5.7               2.5
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

Now you have played around with some of the basics manipulation in pandas! Now lets jump into some challenges

<span style="color:yellow">
<h2>
Yellow excercises 
</span>

**OBS:**  To ensure you can go back in 3 months time and read you code and understand the logics behind it it needs to be well commented.   
So, while you solve the yellow excercises ensure that you add some meaningful comments about the logics and coding choices.  

:))


*The Yellow excercises is borrowed from the 2024 couse written by Ethan Weed*

**Music sales challenge**

Write a script that:

1. Combines the tables of best-selling physical singles and best-selling digital singles on the Wikipedia page "List_of_best-selling_singles"
2. Outputs the artist and single name for the year you were born. If there is no entry for that year, take the closest year after you were born.
3. Outputs the artist and single name for the year you were 15 years old.

In [63]:
# Starter code
url_music = "https://en.wikipedia.org/wiki/List_of_best-selling_singles"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_music, headers=headers)

# Pass the HTML text to pandas
musicdata = pd.read_html(StringIO(response.text))


#Extracting physical and digital singles from the musicdata
physical_singles = musicdata[0]
digital_singles = musicdata[3]

physical_singles["Type"] = "Physical"
digital_singles["Type"] = "Digital"

# Combining the two tables
combined_singles = pd.concat(
    [physical_singles, digital_singles],
    ignore_index=True
)

combined_singles.head()

,Year,Single,Artist,Claimed sales (in million),Ref.,Type,Units (in million)
0,1935.0,"""Silent Night""",Bing Crosby,30.0,[11],Physical,NaN
1,1942.0,"""White Christmas""",Bing Crosby,50.0,[5],Physical,NaN
2,1946.0,"""Petit Papa Noël""",Tino Rossi,30.0,[12],Physical,NaN
3,1954.0,"""Rock Around the Clock""",Bill Haley & His Comets,25.0,[13][14],Physical,NaN
4,1960.0,"""It's Now or Never""",Elvis Presley,20.0,[15][16],Physical,NaN

In [73]:
# Print the artist and single from the year you were born
#Hint: combined_singles[combined_singles['Year']] finds the column with all the years songs were released.

combined_singles[combined_singles['Year'] == 2002.0]

Empty DataFrame
Columns: [Year, Single, Artist, Claimed sales (in million), Ref., Type, Units (in million)]
Index: []

In [74]:
# Print the artist and single from the year you were 15 years old. 

combined_singles[combined_singles['Year'] == 2017.0]

,Year,Single,Artist,Claimed sales (in million),Ref.,Type,Units (in million)
15,2017.0,"""Shape of You""",Ed Sheeran,NaN,[35],Digital,26.6

## Space challenge

1. Make a single dataframe that combines the space missions from the 1950's to the 2020's
2. Write a script that returns the year with the most launches
3. Write a script that returns the most common month for launches
4. Write a script that ranks the months from most launches to fewest launches

In [79]:
# Starter code.
url_space =  "https://en.wikipedia.org/wiki/Timeline_of_Solar_System_exploration"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_space, headers=headers)

# Pass the HTML text to pandas
spacedata = pd.read_html(StringIO(response.text))

# combine all tables into data frame
combined_space = pd.concat(spacedata, ignore_index = True)

# Dropping column we dont need
combined_space = combined_space.iloc[:, 0:3]
combined_space

,Mission name,Launch date,Description
0,Sputnik 1,4 October 1957,First Earth orbiter
1,Sputnik 2,3 November 1957,"Earth orbiter, first animal in orbit, a dog na..."
2,Explorer 1,1 February 1958,Earth orbiter; discovered Van Allen radiation ...
3,Vanguard 1,17 March 1958,Earth orbiter; oldest spacecraft still in Eart...
4,Luna 1,2 January 1959,First lunar flyby (failed lunar impact); first...
...,...,...,...
329,NaN,NaN,NaN
330,NaN,NaN,NaN
331,NaN,NaN,NaN
332,NaN,NaN,NaN
333,NaN,NaN,NaN

In [81]:
## The year with the most launches 
year_count = 0



# Hint:  we want the column 'Launch date', only the rows with a date, and then converteed to a string
# Because a string we can index so we can take the last four digits

In [77]:
# The month with the most launches

In [78]:
# Ranking of months with the most to the fewest launches

## Supervillain challenge

1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's
2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade
3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results in a nice table (pandas dataframe)

In [ ]:
#supervillandata = pd.read_html("https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts")

url_villan = "https://en.wikipedia.org/wiki/List_of_comic_book_supervillain_debuts"

# Add a User-Agent header so Wikipedia doesn't block it
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url_villan, headers=headers)

# Pass the HTML text to pandas
supervillandata = pd.read_html(StringIO(response.text))

# combine all tables into data frame
df_supervillan = pd.concat(supervillandata, ignore_index = True)
df_supervillan.head()

In [ ]:
# 1. Write a script that combines the tables showing supervillain debuts from the 30's through the 2010's

In [ ]:
# 2. Write a script that ranks each decade in terms of how many supervillains debuted in that decade

In [ ]:
# 3. Write a script that ranks the different comics companies in terms of how many supervillains they have, and display the results